server:
  port: 9000
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      properties:
        schema.registry.url: http://localhost:8081
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer