# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
# curl -X PUT "localhost:9200/my_index/_doc/1?pretty" -H 'Content-Type: application/json' -d'

PUT http://localhost:9200/netflow-raw?pretty
Content-Type: application/json

{
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "netflow-raw": {
      "properties": {
        "ackDat": {
          "type": "float"
        },
        "dAppBytes": {
          "type": "long"
        },
        "dHops": {
          "type": "long"
        },
        "dPort": {
          "type": "long"
        },
        "dTos": {
          "type": "long"
        },
        "dTtl": {
          "type": "long"
        },
        "dstAddr": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "dstBytes": {
          "type": "long"
        },
        "dstPkts": {
          "type": "long"
        },
        "dstRate": {
          "type": "float"
        },
        "dstWin": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "dur": {
          "type": "float"
        },
        "label": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "lastTime": {
          "type": "date"
        },
        "proto": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "rate": {
          "type": "float"
        },
        "rcBytes": {
          "type": "long"
        },
        "sAppBytes": {
          "type": "long"
        },
        "sHops": {
          "type": "long"
        },
        "sPort": {
          "type": "long"
        },
        "sTos": {
          "type": "long"
        },
        "sTtl": {
          "type": "long"
        },
        "srcAddr": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "srcPkts": {
          "type": "long"
        },
        "srcRate": {
          "type": "float"
        },
        "srcWin": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "startTime": {
          "type": "date"
        },
        "state": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "synAck": {
          "type": "float"
        },
        "tcpRtt": {
          "type": "float"
        },
        "totAppByte": {
          "type": "long"
        },
        "totBytes": {
          "type": "long"
        },
        "totPkts": {
          "type": "long"
        }
      }
    }
  }
}

